import pandas as pd
import numpy as np


def rename_synonyms(df: pd.DataFrame) -> pd.DataFrame:
    # replace every space
    df = df.replace(' ', '', regex=True)

    # upper
    df['team_1'] = df['team_1'].str.upper()
    df['team_2'] = df['team_2'].str.upper()

    # dictionary of synonym replacements
    synonyms = {
        'G.ZABRZE': 'GÓRNIKZABRZE',
        'GÓRNIKZ.': 'GÓRNIKZABRZE',
        'Z.LUBLIN': 'ZAGŁĘBIELUBLIN',
        'ZAGŁĘBIEL.': 'ZAGŁĘBIELUBLIN',
        'LUBLIN': 'ZAGŁĘBIELUBLIN',
        'TYCHY': 'GKSTYCHY',
        'ARKA': 'ARKAGDYNIA',
        'SKRACZ.': 'SKRACZĘSTOCHOWA',
        'CHOJNICE': 'CHOJNICZANKACHOJNICE',
        'W.KRAKÓW': 'WISŁAKRAKÓW',
        'NIECIECZA': 'TERMALICANIECIECZA',
        'BRUK-BETTERMALICANIECIECZA': 'TERMALICANIECIECZA',
        'TERMALICABRUK-B.': 'TERMALICANIECIECZA',
        'OPOLE': 'ODRAOPOLE',
        'CHOJNICZANKA': 'CHOJNICZANKACHOJNICE',
        'CHOJNICZANKACHO.': 'CHOJNICZANKACHOJNICE',
        'MKSCHOJNICZANKACHOJNICE': 'CHOJNICZANKACHOJNICE',
        'PUSZCZANIEPOŁOM.': 'PUSZCZANIEPOŁOMICE',
        'NIEPOŁOMICE': 'PUSZCZANIEPOŁOMICE',
        'SOSNOWIEC': 'ZAGŁĘBIESOSNOWIEC',
        'ZAGŁĘBIESOSNOWI.': 'ZAGŁĘBIESOSNOWIEC',
        'CWKSRESOVIA': 'RESOVIA',
        'RESOVIARZESZÓW': 'RESOVIA',
        'PODBESKIDZIEBIE.': 'PODBESKIDZIE',
        'TSPODBESKIDZIEBIELSKO-BIAŁA': 'PODBESKIDZIE',
        'ŁĘCZNA': 'GÓRNIKŁĘCZNA',
        'G.ŁĘCZNA': 'GÓRNIKŁĘCZNA',
        'SANDECJA': 'SANDECJANOWYSĄCZ',
        'CHORZÓW': 'RUCHCHORZÓW',
        'GŁOGÓW': 'CHROBRYGŁOGÓW',
        'CHROBRYII': 'CHROBRYGŁOGÓWII',
        'CHROBRYIIGLOGOW': 'CHROBRYGŁOGÓWII',
        'SANDECJANOWYSĄ.': 'SANDECJANOWYSĄCZ',
        'BŁONIANKA': 'BŁONIANKABŁONIE',
        'GEDANIAG.': 'GEDANIAGDAŃSK',
        'HUTNIKK.': 'HUTNIKKRAKÓW',
        'J.JAROCIN': 'JAROTAJAROCIN',
        'JKSJAROTAJAROCIN': 'JAROTAJAROCIN',
        'K.KOŁOBRZEG': 'KOTWICAKOŁOBRZEG',
        'U.SWARZĘDZ': 'UNIASWARZĘDZ',
        'Z.PRUSZKÓW': 'ZNICZPRUSZKÓW',
        'LEGIAII': 'LEGIAIIWARSZAWA',
        'U.SKIERNIEWICE': 'UNIASKIERNIEWICE',
        'MIEDŹIILEGNICA': 'MIEDŹLEGNICAII',
        'MKSMIEDŹLEGNICAII': 'MIEDŹLEGNICAII',
        'MIEDŹII': 'MIEDŹLEGNICAII',
        'OLIMPIAE.': 'OLIMPIAELBLĄG',
        'ZKSOLIMPIAELBLĄG': 'OLIMPIAELBLĄG',
        'LEGIONOVIA': 'LEGIONOVIALEGIONOWO',
        'POLONIAŚRODAWLKP.': 'POLONIAŚRODAWIELKOPOLSKA',
        'ŚRODAWLKP.': 'POLONIAŚRODAWIELKOPOLSKA',
        'POLONIAW.': 'POLONIAWARSZAWA',
        'MOTORL.': 'MOTORLUBLIN',
        'S.OLSZTYN': 'STOMILOLSZTYN',
        'R.STĘŻYCA': 'RADUNIASTĘŻYCA',
        'G.TARNOWSKIEGÓRY': 'GWAREKTARNOWSKIEGÓRY',
        'TSGWAREKTARNOWSKIEGÓRY': 'GWAREKTARNOWSKIEGÓRY',
        'RAKÓWII': 'RAKÓWCZĘSTOCHOWAII',
        'RAKÓWIICZĘSTOCHOWA': 'RAKÓWCZĘSTOCHOWAII',
        'ŚLĄSKII': 'ŚLĄSKWROCŁAWII',
        'ŚLĄSKIIWROCŁAW': 'ŚLĄSKWROCŁAWII',
        'KPSTAROGARD': 'STAROGARDGDAŃSKI',
        'KPSTAROGARDGDAŃSKI': 'STAROGARDGDAŃSKI',
        'WARTAGORZÓWWLKP.': 'WARTAGORZÓWWIELKOPOLSKI',
        'W.GORZÓWWLKP.': 'WARTAGORZÓWWIELKOPOLSKI',
        'LKSGOCZAŁKOWICE-ZDRÓJ': 'LKSGOCZAŁKOWICEZDRÓJ',
        'GOCZAŁKOWICEZDRÓJ': 'LKSGOCZAŁKOWICEZDRÓJ',
        'LKSGOCZAŁKOWICE': 'LKSGOCZAŁKOWICEZDRÓJ',
        'REKORDBIELSKO-BIAŁA': 'BTSREKORDBIELSKO-BIAŁA',
        'REKORDBB': 'BTSREKORDBIELSKO-BIAŁA',
        'ZAWISZAB.': 'ZAWISZABYDGOSZCZ',
        'P.ŁOWICZ': 'PELIKANŁOWICZ',
        'BAŁTYKG.': 'BAŁTYKGDYNIA',
        'ŁKSII': 'ŁKSŁÓDŹII',
        'ŁKSIIŁÓDŹ': 'ŁKSŁÓDŹII',
        'U.SOLECKUJ.': 'UNIASOLECKUJAWSKI',
        'URSUSW.': 'URSUSWARSZAWA',
        'V.WOLIN': 'VINETAWOLIN',
        'LECHII': 'LECHPOZNAŃII',
        'W.SIERADZ': 'WARTASIERADZ',
        'ZAGŁĘBIEII': 'ZAGŁĘBIELUBINII',
        'ZAGŁĘBIEIILUBIN': 'ZAGŁĘBIELUBINII',
        'KKS1925KALISZ': 'KKSKALISZ',
        'B.RADOM': 'BROŃRADOM',
        'B.STARGARD': 'BŁĘKITNISTARGARD',
        'P.BIAŁOBRZEGI': 'PILICABIAŁOBRZEGI',
        'KSSTALBRZEG': 'BTPSTALBRZEG',
        'STALBRZEG': 'BTPSTALBRZEG',
        'S.KLECZEW': 'SOKÓŁKLECZEW',
        'ŚLĘZAW.': 'ŚLĘZAWROCŁAW',
        'WISŁAPUŁAWY': 'KSWISŁAPUŁAWY',
        'W.PUŁAWY': 'KSWISŁAPUŁAWY',
        'JAGIELLONIAII': 'JAGIELLONIAIIBIAŁYSTOK',
        'NOWYDWÓRMAZ.': 'ŚWITNOWYDWÓRMAZ.',
        'C.GUBIN': 'MKPCARINAGUBIN',
        'CARINAGUBIN': 'MKPCARINAGUBIN',
        'S.TARNOBRZEG': 'KSSIARKATARNOBRZEG',
        'SIARKATARNOBRZEG': 'KSSIARKATARNOBRZEG',
        'MŁAWIANKA': 'MŁAWIANKAMŁAWA',
        'O.GRUDZIĄDZ': 'OLIMPIAGRUDZIĄDZ',
        'P.BYTOM': 'POLONIABYTOM',
        'G.POLKOWICE': 'GÓRNIKPOLKOWICE',
        'KSPOLKOWICE': 'GÓRNIKPOLKOWICE',
        'KSZOOSTROWIECŚW.': 'KSZOOSTROWIECŚWIĘTOKRZYSKI',
        'KORONAIIKIELCE': 'KORONAKIELCEII',
        'O.ZAMBRÓW': 'OLIMPIAZAMBRÓW',
        'POGOŃIISZ.': 'POGOŃSZCZECINII',
        'POGOŃIISZCZECIN': 'POGOŃSZCZECINII'

    }

    df = df.replace({"team_1": synonyms,
                    "team_2": synonyms})

    # print(df)

    return df


# testing input
# df = pd.read_excel(
#     'D:\\Edukacja\\Projekty\\arbitrage_betting\\output\\20230527_144257.xlsx')[["team_1",  "team_2"]]
# rename_synonyms(df)

# print(df)
