synonyms_ufc = {
    'A.NUNES': 'AMANDANUNES',
    'NUNESA.': 'AMANDANUNES',
    'NUNESAMANDA': 'AMANDANUNES',
    'I.ALDANA': 'IRENEALDANA',
    'IRENEA.': 'IRENEALDANA',
    'ALDANAIRENE': 'IRENEALDANA',
    'FLICKJ.': 'JIMMYFLICK',
    'FLICKJIMMY': 'JIMMYFLICK',
    'RODRIGUEZY.': 'YAIRRODRIGUEZ',
    'VOLKANOVSKIA.': 'ALEXVOLKANOVSKI',
    'STERLINGA.': 'ALJAMAINSTERLING',
    'OMALLEYS.': 'SEANOMALLEY',
    'O`MALLEYS.': 'SEANOMALLEY',
    'BARRIAULTM.A.': 'MARCANDREBARRIAULT',
    'BARRIAULTMARCA.': 'MARCANDREBARRIAULT',
    'M.BARRIAULT': 'MARCANDREBARRIAULT',
    'MARCANDREBARRIAULT': 'MARCANDREBARRIAULT',


    '': ''
    # ufc
}